version: '3.8'

services:
  core-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
    volumes:
      - .:/app
    restart: unless-stopped
    # Configure network
    networks:
      - app-network

networks:
  app-network:
    driver: bridge